name: Mirror commits to cpp-pbni-framework
on:
  push:
    branches:
      - main

jobs:
  commits:
    runs-on: [self-hosted, windows]

    steps:
      - name: Pull
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set Remote
        continue-on-error: true # sometimes the remote is already there, in which case this errors
        run: git remote add mirror git@github.com:informaticon/cpp-pbni-framework.git

      - name: Setup SSH Key
        uses: webfactory/ssh-agent@dc588b651fe13675774614f8e6a936a468676387 # v0.9.0
        with:
          ssh-private-key: ${{ secrets.CPP_PBNI_FRAMEWORK_PRIVATE_KEY }}

      - name: Push
        run: |
          git push mirror main
          git push mirror main --tags
